export * from "./calendar";
export * from "./detail";
export * from "./add";
export * from "./list";
export * from "./auth";
export * from "./settingsPage";
export * from "./forgotPassword";
export {default as AddPage} from "./AddPage";
export {default as StartPage} from "./StartPage";
export {default as AgendaPage} from "./agenda/AgendaPage";
